import Quickshell
import Quickshell.Widgets
import QtQuick
import QtQuick.Layouts
import QtQuick.Effects
import QtQuick.Controls
import qs.config
import qs.modules.components
import qs.modules.functions
import qs.services

StyledRect {
    id: root

    property bool hovered: false
    property bool selected: false
    required property int parentWidth

    readonly property bool isGrid: Config.runtime.launcher.layout === "grid"
    readonly property int gridColumns: 5
    readonly property int gridSpacing: Metrics.spacing(10)
    readonly property int gridTileSize: Math.floor((parentWidth - (gridColumns + 1) * gridSpacing) / gridColumns)

    width: isGrid ? gridTileSize : parentWidth
    height: isGrid ? gridTileSize : 50
    radius: Metrics.radius(15)

    color: (hovered || selected)
        ? Appearance.m3colors.m3surfaceContainerHigh
        : Appearance.m3colors.m3surfaceContainer

    Behavior on color {
        PropertyAnimation { duration: Metrics.chronoDuration(200); easing.type: Easing.InSine }
    }

    // GRID VIEW
    Column {
        visible: isGrid
        anchors.centerIn: parent
        spacing: Metrics.spacing(6)

        ClippingWrapperRectangle {
            id: gridIcon
            anchors.horizontalCenter: parent.horizontalCenter
            property int size: Math.round(root.gridTileSize * 0.5)
            width: size
            height: size
            radius: Metrics.radius(12)
            color: "transparent"

            child: Image {
                source: AppRegistry.iconForDesktopIcon(modelData.icon) || Quickshell.iconPath("application-x-executable")
                fillMode: Image.PreserveAspectFit
                layer.enabled: true
                layer.effect: MultiEffect {
                    saturation: (Config.runtime.appearance.tintIcons ||
                        (Config.runtime.appearance.colors.matugenScheme === "scheme-monochrome" &&
                         Config.runtime.appearance.colors.autogenerated) ||
                        Config.runtime.appearance.colors.scheme.toLowerCase() === "monochrome") ? -1.0 : 1.0
                }
            }
        }

        StyledText {
            anchors.horizontalCenter: parent.horizontalCenter
            text: modelData.name
            font.pixelSize: Metrics.fontSize(14)
            horizontalAlignment: Text.AlignHCenter
            width: root.gridTileSize - Metrics.margin(8)
            elide: Text.ElideRight

            Behavior on color {
                PropertyAnimation { duration: Metrics.chronoDuration(200); easing.type: Easing.InSine }
            }
        }
    }

    // LIST VIEW
    ClippingWrapperRectangle {
        id: entryIcon
        visible: !isGrid
        anchors.left: parent.left
        anchors.leftMargin: Metrics.margin(10)
        anchors.verticalCenter: parent.verticalCenter

        property int size: 25
        width: size
        height: size
        radius: Metrics.radius(1000)
        color: "transparent"

        child: Image {
            source: AppRegistry.iconForDesktopIcon(modelData.icon) || Quickshell.iconPath("application-x-executable")
            fillMode: Image.PreserveAspectFit
            layer.enabled: true
            layer.effect: MultiEffect {
                saturation: (Config.runtime.appearance.tintIcons ||
                    (Config.runtime.appearance.colors.matugenScheme === "scheme-monochrome" &&
                     Config.runtime.appearance.colors.autogenerated) ||
                    Config.runtime.appearance.colors.scheme.toLowerCase() === "monochrome") ? -1.0 : 1.0
            }
        }
    }

    ColumnLayout {
        visible: !isGrid
        anchors.left: entryIcon.right
        anchors.leftMargin: Metrics.margin(10)
        anchors.verticalCenter: parent.verticalCenter
        height: 40
        spacing: Metrics.spacing(-5)

        StyledText {
            text: modelData.name
            font.pixelSize: Metrics.fontSize(14)
            font.weight: 400

            Behavior on color {
                PropertyAnimation { duration: Metrics.chronoDuration(200); easing.type: Easing.InSine }
            }
        }

        StyledText {
            text: StringUtils.shortText(modelData.comment, 65)
            font.pixelSize: Metrics.fontSize(12)
            font.weight: 400
            color: hovered || selected
                ? Qt.alpha(Appearance.m3colors.m3onSurface, 0.7)
                : Qt.alpha(Appearance.colors.colOutline, 0.7)

            Behavior on color {
                PropertyAnimation { duration: Metrics.chronoDuration(200); easing.type: Easing.InSine }
            }
        }
    }

    MouseArea {
        anchors.fill: parent
        hoverEnabled: true
        cursorShape: Qt.PointingHandCursor
        onEntered: root.hovered = true
        onExited: root.hovered = false
        onClicked: {
            modelData.execute()
            Globals.visiblility.launcher = false;
        }
    }
}